/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CounterImport } from './routes/counter'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ClientsIndexImport } from './routes/clients/index'
import { Route as ClientsLayoutImport } from './routes/clients/_layout'
import { Route as ClientsClientIdImport } from './routes/clients/$clientId'

// Create Virtual Routes

const ClientsImport = createFileRoute('/clients')()

// Create/Update Routes

const ClientsRoute = ClientsImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRoute,
} as any)

const CounterRoute = CounterImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClientsIndexRoute = ClientsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)

const ClientsLayoutRoute = ClientsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ClientsRoute,
} as any)

const ClientsClientIdRoute = ClientsClientIdImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterImport
      parentRoute: typeof rootRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdImport
      parentRoute: typeof rootRoute
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsImport
      parentRoute: typeof rootRoute
    }
    '/clients/_layout': {
      id: '/clients/_layout'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsLayoutImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexImport
      parentRoute: typeof ClientsImport
    }
  }
}

// Create and export the route tree

interface ClientsRouteChildren {
  ClientsLayoutRoute: typeof ClientsLayoutRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsLayoutRoute: ClientsLayoutRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsLayoutRoute
  '/clients/': typeof ClientsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsRouteWithChildren
  '/clients/_layout': typeof ClientsLayoutRoute
  '/clients/': typeof ClientsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/counter'
    | '/clients/$clientId'
    | '/clients'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/counter' | '/clients/$clientId' | '/clients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/counter'
    | '/clients/$clientId'
    | '/clients'
    | '/clients/_layout'
    | '/clients/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CounterRoute: typeof CounterRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsRoute: typeof ClientsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CounterRoute: CounterRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsRoute: ClientsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/counter",
        "/clients/$clientId",
        "/clients"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/counter": {
      "filePath": "counter.tsx"
    },
    "/clients/$clientId": {
      "filePath": "clients/$clientId.tsx"
    },
    "/clients": {
      "filePath": "clients",
      "children": [
        "/clients/_layout",
        "/clients/"
      ]
    },
    "/clients/_layout": {
      "filePath": "clients/_layout.tsx",
      "parent": "/clients"
    },
    "/clients/": {
      "filePath": "clients/index.tsx",
      "parent": "/clients"
    }
  }
}
ROUTE_MANIFEST_END */
